title: "Guildless Gamers"
email: theguildlessgamers@gmail.com
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.svg'
author: Thonk
paginate: 30
disqus: 'guildless discussions'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  thonk:
    name: Guildless Gamers
    display_name: Thonk
    avatar: 'assets/images/sal.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/guildlessgamers
    description: "Guildless Gamers co-admin"
  grawrz:
    name: Grawrz
    display_name: Grawrz
    avatar: 'assets/images/john.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/grawrzguide
    description: "Grawrz - dashingly handsome but even more skillful"
  tanjimon:
    name: Tanjimon
    display_name: Tanjimon
    avatar: 'assets/images/tanj_ron.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/Tanjimon
    description: "Always on the ball"

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/guildlessgamers

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives