title: "Donjet Rexhepi"
email: solida@students.uni-marburg.de
timezone: UTC
baseurl: ""
url: "https://donjetr.github.io"
logo: 'assets/images/logo.png'
favicon: 'assets/images/circle.ico'
author: Donjet Rexhepi
paginate: 30
disqus: 'demowebsite'
locale: en
lang: en
permalink: /:categories/:year/:month/:day/:title/
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed


# Authors
authors:
  donjet:
    name: Donjet Rexhepi
    display_name: Donjet Rexhepi
    avatar: 'assets/images/sl.JPEG'
    email: donjet@students.uni-marburg.de
    description: "donjet studied Computer Science at Philipps-Universität Marburg"

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
