title: "Guildless Gamers"
email: theguildlessgamers@gmail.com
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.svg'
author: Thonk
paginate: 30
disqus: guildless.disqus.com
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: GTM-PDQLS3RR

icon-size: 35

description: Checkout the Guildless Gamers, the best community in Web3!
image: 'assets/images/ray-header.png'

# Admins
admins:
  thonk: 
    name: Thonk
    role: Vision and Partnerships
    image: 'assets/images/cc/thonk.jpg'
    twitter: https://twitter.com/OgThonk
  nichee:
    name: Nichee
    role: Branding and Design
    image: 'assets/images/cc/nichee.jpg'
    twitter: https://twitter.com/nicheesan
  winty:
    name: Winty
    role: Analysis and Content Creation
    image: 'assets/images/cc/winty.jpg'
    twitter: https://twitter.com/Winty_Axie
  bewm:
    name: Bewm
    role: Head Moderator and In-server activity
    image: 'assets/images/cc/bewm.jpg'
    twitter: https://twitter.com/bewm24
  grawrz:
    name: Grawrz
    role: Guildless Creator Program
    image: 'assets/images/cc/grawrz-oshio.png'
    twitter: https://twitter.com/GrawrzGuide



# Authors
authors:
  thonk:
    name: Guildless Gamers
    display_name: Thonk
    avatar: 'assets/images/sal.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/guildlessgamers
    description: "Guildless Gamers co-admin"
  guildless:
    name: Guildless Gamers
    display_name: Guildless Gamers
    avatar: 'assets/images/logo-resized.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/guildlessgamers
    description: "Guildless Gamers - the best non-guild 'guild' in Web3"
  tanjimon:
    name: Tanjimon
    display_name: Tanjimon
    avatar: 'assets/images/tanj_ron.png'
    email: theguildlessgamers@gmail.com
    web: https://thonksquad.github.io/
    twitter: https://twitter.com/Tanjimon
    description: "Always on the ball"

# Partners
partners:
  skysmash:
    name: Sky Smash
    logo: 'assets/images/partners/skysmash-logo.png'
    twitter: https://twitter.com/skysmashaxie
  roninradio:
    name: Ronin Radio
    logo: 'assets/images/partners/roninradio-logo.png'
    twitter: https://twitter.com/theroninradio
    css: ronin-radio-logo

# Creators
creators:
  grawrz:
    name: Grawrz
    role: Twitch Streamer, Youtuber
    avatar: 'assets/images/cc/grawrz.png'
    twitch: https://twitch.tv/GrawrzGuide
    youtube: https://youtube.com/GrawrzGuide
    twitter: https://twitter.com/GrawrzGuide
    description: "Everyone's favorite doggo VTuber! Streamer, Despairer, Shoutcaster!"
  nichee:
    name: Nichee
    role: Twitch Streamer, Youtuber, Artist
    avatar: 'assets/images/cc/nichee.png'
    twitch: https://twitch.tv/nicheesan
    twitter: https://twitter.com/nicheesan
    description: "Daydreamer artist who does streams like a potato"
  atown71:
    name: Atown71
    role: Twitch Streamer
    avatar: 'assets/images/cc/atown.png'
    twitch: https://twitch.tv/atown71
    twitter: https://twitter.com/AdrianMalkowsk1
    description: "FPS enjoyer, casual whale in Axie. What is money? Only Paper"
  1ogic:
    name: 1ogic
    role: Content Creator
    avatar: 'assets/images/cc/1ogic.png'
    twitch: https://twitch.tv/1_ogic
    youtube: https://youtube.com/@1_ogic
    twitter: https://twitter.com/1_ogic
    description: "Min/max’er, content creator, PvP floor janitor"

# Social
social:
  twitch: https://twitch.tv/guildlessgamers
  youtube: https://www.youtube.com/@GuildlessGamers
  twitter: https://twitter.com/guildlessgamers

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives